### ISSUE TITLE
Can not generate boilerplate

### ISSUE THREAD

**Issue by leonleonleon** [leifmarcus/create-react-web#1]
Installing seems fine but when i run:

`create-react-web --redux --router`

i get the following error:

```
create folder structure
-----------------------
Error: Error: ENOENT: no such file or directory, mkdir '/Users/leonreindl/web/playground/my-new-project/src/components'
    at createFolders (/usr/local/lib/node_modules/@leif_marcus/create-react-web/lib/utils/folders.js:24:15)
    at <anonymous>
```

Any Ideas?

**Comment by leifmarcus** [comment]
might be that you have not the rights set correctly. You can try to run it with `sudo`. Also it might be related to the node version you are using. I tested it with node v10.14.1. Did you try an update?

The recursive option for `mkDir` function was added in the last year to node. maybe it is not in your version.

**Comment by leifmarcus** [comment]
this was related to an old node version.
